remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - general-rules.md
  - technical-rules.md
  - game-field.md
  - robot.md
