title: "STEAMxD"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: false

# include:
#   - general-rules.md
#   - technical-rules.md
#   - game-field.md
#   - robot.md
